### ISSUE TITLE
Duplication of blocks

### ISSUE THREAD

**Issue by PragmaticPhil** [xinabox/pxt-SL06#3]
We have 2 functions that do the same thing:

1= SL06 enable proximity sensor (boolean)
2 = SL06 disable proximity sensor

NB - the same is true for Light and Gesture modes.

I cannot see a need for (2) - it just confuses me having both options.

Please can do either of the following:
... let me know if there is a good reason for the duplication
... remove the (2) functions.

Note - the library is long so removing (2) is my preferred approach.

**Comment by KalbeAbbas** [comment]
Updated functions name and removed unnecessary ones.

**Comment by gotfredsen** [comment]
@PragmaticPhil pls close if solved.

**Comment by PragmaticPhil** [comment]
Thank you :)
