### ISSUE TITLE
SL06 - set mode

### ISSUE THREAD

**Issue by PragmaticPhil** [xinabox/pxt-SL06#5]
Now that we have our set mode blocks sorted I find there is a UX issue.

... when a user tries to set SL06 to Gesture mode WE KNOW that we need to turn off Proximity and Light mode.

... why would we make them do it explicitly?   
It leads to scenarios where the BEST (safest) way to enable any single mode is with 3 blocks:

![Picture2](https://user-images.githubusercontent.com/10323597/77342538-3eec1480-6d28-11ea-9a8a-7960623f102b.png)

_[Image is meant to show SL06 Disable Light as second block]_

Please can we consider the possibilitity of have ONE block to set mode.  It has options (Gesture, Light and Proximity) and whichever one is explicitly being turned onm we implicitly turn the other 2 off.

This new Set Mode block would be available through the extension in a group called Mode.  This group would be displayed at the top.

**Comment by gotfredsen** [comment]
Yes, lets do that: @KalbeAbbas

**Comment by KalbeAbbas** [comment]
Done.

**Comment by PragmaticPhil** [comment]
Thanks.  2 things before I close the ticket:

1 = please move the Mode blocks to the top of the library.
2 = please move the Gesture blocks to the end... as long as its not working I don't want them at the top!

Happy to close when these are complete :)
