### ISSUE TITLE
SL06 - Gesture - Usability amends

### ISSUE THREAD

**Issue by PragmaticPhil** [xinabox/pxt-SL06#6]
The Gesture blocks make it very difficult for microbit MakeCode users to use the gesture sensing.

1 = users have no scope of the return values (e.g. they have a no way of knowing what is returned for a left swipe - is it "LEFT", "Left", "left", "West" etc.

Finding this out through trial-and-error is not a positive user experience.  Quite the opposite:

2 = Non-sophisticated users should not be expected to have the skills to easily find this out.

3 = Writing a test program to output the values onto the microbit 5x5 LED matrix is just not feasible  due to how rubbish the display is.  I have an OD01, we can't rely on everyone who has an SL06 having an OD01).

Note also the snippet attached.  I understand why it doesn't work, but our core target market for this product won't:

![Picture3](https://user-images.githubusercontent.com/10323597/77911394-a6561700-7288-11ea-8c14-71bc7ffad984.png)

UX requirements follow...

**Comment by PragmaticPhil** [comment]
ISSUE 1: the SL06 gesture return value updates every time the block is used.  That means that the SL06 Gesture block can only be used once per non-NONE gesture - users will have to be clever to ensure it is only called once per forever loop iteration.  The snippet posted above shows a use case where this limitation is a problem and I can think of many others.

ISSUE 2:  our return type is String.  MakeCode does not allow variables of String type.  
So we can't easily save the SL06 return value to a variable to use in a forever loop iteration.  
... even if we could, asking non-techie users to do this is not a great UX thing.

We need to make it significantly easier for our target users.

SOLUTION 
my proposed solution involves 8 blocks - I am open to other solutions that address the issues and provide a decent UX:

Block 1:
**Read SL06 gesture.**
... this block polls the SL06 and HAS NO RETURN VALUE in MakeCode.
... when this is called we set a variable somewhere and that variable is not updated until this is called again.
... NB - **ALL the blocks below, blocks 2 - 8, are calculated BASED ON THE VALUE IN THIS VARIABLE.** 
So the SL06 value used to calculate the blocks below DOES NOT CHANGE unless **Read SL06 gesture** is called again.

Typically a user will have to call this at the beginning of their forever loop (or equivalent).  It is NOT ideal - it is a workaround : fixing the return value of SL06 gesture so that it doesn't change during a cycle is ideal.  
But this method, with documentation, is logical and usable enough

Block 2: 
**SL06 get gesture name.**
... this returns a STRING that corresponds to the 'fixed' value that has been set when the **Read SL06 gesture.** is called.

Block 3: 
**SL06 get gesture ID.**
... this returns an Integer that corresponds to the 'fixed' value that has been set when the **Read SL06 gesture.** is called.

We might be able to do away with Block 2 and / or Block 3... I would say lets include them to ensure we are providing a thorough set of blocks.

Blocks 4 - 8:
... create 5 blocks that each return a boolean.
**SL06 no Gesture recorded**
**SL06 Gesture is Up**
**SL06 Gesture is Down**
**SL06 Gesture is Left**
**SL06 Gesture is Right**

Observation: using this approach users could infer another 4 swipe direction (Up AND left, Up and Right etc)

**Comment by gotfredsen** [comment]
So the right way to do this is to have a `on event` approach.
<img width="909" alt="Screenshot 2020-04-01 at 1 10 57 PM" src="https://user-images.githubusercontent.com/2776277/78130839-514a0a80-741a-11ea-8cd5-190a08914eae.png">
Notice in this screenshot, then `on radio received <variable>`. Similarly we should do a `SL06 on gesture <variable>`, where the <variable> is the gesture - as a dropdown - we are expecting. Then only when that gesture happens it fires of the event.

**Comment by PragmaticPhil** [comment]
Yes please.  This is a MUCH better solution that the one I proposed.

**Comment by PragmaticPhil** [comment]
Thanks - the new blocks work very well :)
... the Towards gesture is hard to trigger, but that is understandable and acceptable.

I also like that the gesture is 'fetched' by the Read Gesture.  I've looked at the Grove gesture library and I think they suffer from the issue we avoid by doing it this way (but I don't have their kit to test it).

Please confirm the following:
IF i set Mode to Gesture, then use Read Gesture... 
... Can I then set Mode to Light and use the Light functionality AS WELL as the gesture event blocks?
i.e. do I have to be in Gesture mode to use the gesture event blocks AFTER I've read gesture?
As the image below:
![Picture3](https://user-images.githubusercontent.com/10323597/78502868-2e419280-775b-11ea-93a2-8b912148d0f8.png)

One final amend please:
... with the event blocks please parametise the gesture type
... so there is ONE event block with a parameter to choose the different gesture type.

**Comment by PragmaticPhil** [comment]
Thank you :)
